WebAppTest/Models/AbonamentViewModel.cs
namespace WebAppTest.Models
{
    public class AbonamentViewModel
    {
        public int Id { get; set; }
        public string Nume { get; set; }
        public decimal Pret { get; set; }
        public int Durata { get; set; }
        public string Beneficii { get; set; }
    }
}

WebAppTest/Controllers/AbonamentController.cs
using Repository_DBFirst;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppTest.Models;

namespace WebAppTest.Controllers
{
    public class AbonamentController : Controller
    {
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Session["UserId"] == null)
            {
                filterContext.Result = RedirectToAction("Login", "Account");
            }
            base.OnActionExecuting(filterContext);
        }
        private readonly photoeditEntities _context;

        public AbonamentController(photoeditEntities context)
        {
            _context = context;
        }
        public AbonamentController() : this(new photoeditEntities())
        {
        }
        public ActionResult Index()
        {
            var abonaments = _context.Abonamente.ToList();

            return View(abonaments);
        }
        public ActionResult Details(int id)
        {
            var abonament = _context.Abonamente
               .FirstOrDefault(u => u.id == id);
            if (abonament == null)
            {
                return HttpNotFound();
            }

            return View(abonament);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AbonamentViewModel abonamentviewmodel)
        {
            if (ModelState.IsValid)
            {
                var abonament = new Abonamente
                {
                    nume = abonamentviewmodel.Nume,
                    pret = abonamentviewmodel.Pret,
                    durata = abonamentviewmodel.Durata,
                    beneficii = abonamentviewmodel.Beneficii
                };
                _context.Abonamente.Add(abonament);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(abonamentviewmodel);
        }
        public ActionResult Edit(int id)
        {
            var abonament = _context.Abonamente.Find(id);
            if (abonament == null)
            {
                return HttpNotFound();
            }

            var abonamentviewmodel = new AbonamentViewModel
            {
                Id = abonament.id,
                Nume = abonament.nume,
                Pret = abonament.pret,
                Durata = abonament.durata,
                Beneficii = abonament.beneficii
            };
            return View(abonamentviewmodel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AbonamentViewModel abonamentViewModel)
        {
            if (ModelState.IsValid)
            {
                var abonament = _context.Abonamente.Find(abonamentViewModel.Id);
                if (abonament == null)
                {
                    return HttpNotFound();
                }

                abonament.nume = abonamentViewModel.Nume;
                abonament.pret = abonamentViewModel.Pret;
                abonament.durata = abonamentViewModel.Durata;
                abonament.beneficii = abonamentViewModel.Beneficii;

                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(abonamentViewModel);
        }
    }
}

WebAppTest/Views/Abonament/Create.cshtml
@model WebAppTest.Models.AbonamentViewModel


<h2>Create Abonament</h2>

@using (Html.BeginForm())
            {
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>Abonament</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.Nume, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nume, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nume, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Pret, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pret, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pret, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Durata, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Durata, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Durata, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Beneficii, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Beneficii, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Beneficii, "", new { @class = "text-danger" })

        </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" style="padding:10px;padding-left:0px;">
            <input type="submit" value="Creează" class="btn btn-primary" />
        </div>
    </div>
    </div>
</div>
}
<a href="@Url.Action("Index", "Abonament")" class="btn btn-secondary">Înapoi</a>

WebAppTest/Views/Abonament/Details.cshtml
@model Repository_DBFirst.Abonamente

<h2>Detalii Abonament</h2>

<div>
    <h4>@Model.nume</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">ID</dt>
        <dd class="col-sm-10">@Model.id</dd>

        <dt class="col-sm-2">Pret</dt>
        <dd class="col-sm-10">@Model.pret</dd>

        <dt class="col-sm-2">Durata</dt>
        <dd class="col-sm-10">@Model.durata</dd>

        <dt class="col-sm-2">Beneficii</dt>
        <dd class="col-sm-10">@Model.beneficii</dd>
    </dl>
</div>
<a href="@Url.Action("Index", "Abonament")" class="btn btn-secondary">Înapoi</a>

WebAppTest/Views/Abonament/Edit.cshtml
@model WebAppTest.Models.AbonamentViewModel


<h2>Edit Abonament</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Abonament</h4>
        <hr />
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Nume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nume, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Pret, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pret, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pret, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Durata, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Durata, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Durata, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Beneficii, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Beneficii, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Beneficii, "", new { @class = "text-danger" })

            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="padding:10px;padding-left:0px;">
                <input type="submit" value="Editează" class="btn btn-primary" />
            </div>
        </div>
       </div>
}
<a href="@Url.Action("Index", "Abonament")" class="btn btn-secondary">Înapoi</a>

WebAppTest/Views/Abonament/Index.cshtml
@model IEnumerable<Repository_DBFirst.Abonamente>

<h2>Abonamente List</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Nume</th>
        <th>Pret</th>
        <th>Durata</th>
        <th>Beneficii</th>
        <th>Detalii</th>
        <th>Editeaza</th>
    </tr>
    @foreach (var abonament in Model)
    {
        <tr>
            <td>@abonament.id</td>
            <td>@abonament.nume</td>
            <td>@abonament.pret</td>
            <td>@abonament.durata</td>
            <td>@abonament.beneficii</td>
            <td>
                <a href="@Url.Action("Details", "Abonament", new { id = abonament.id })" class="btn btn-info">Detalii</a>
            </td>
            <td>
                <a href="@Url.Action("Edit", "Abonament", new { id = abonament.id })" class="btn btn-info">Edit</a>
            </td>
        </tr>
    }
</table>
<div>
    <a href="@Url.Action("Create", "Abonament")" class="btn btn-info">Create</a>
</div>